/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasNovaRouteImport } from './routes/propostas.nova'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AdminDatabaseStatusRouteImport } from './routes/admin.database-status'
import { Route as PropostasIdEditarRouteImport } from './routes/propostas.$id.editar'
import { Route as ClientesIdEditarRouteImport } from './routes/clientes.$id.editar'

const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasNovaRoute = PropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PropostasRoute,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropostasRoute,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const AdminDatabaseStatusRoute = AdminDatabaseStatusRouteImport.update({
  id: '/admin/database-status',
  path: '/admin/database-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdEditarRoute = PropostasIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => PropostasIdRoute,
} as any)
const ClientesIdEditarRoute = ClientesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ClientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/admin/database-status': typeof AdminDatabaseStatusRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/propostas/$id': typeof PropostasIdRouteWithChildren
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/propostas/$id/editar': typeof PropostasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/admin/database-status': typeof AdminDatabaseStatusRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/propostas/$id': typeof PropostasIdRouteWithChildren
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/propostas/$id/editar': typeof PropostasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/admin/database-status': typeof AdminDatabaseStatusRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/propostas/$id': typeof PropostasIdRouteWithChildren
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/propostas/$id/editar': typeof PropostasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/propostas'
    | '/admin/database-status'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes/$id/editar'
    | '/propostas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/propostas'
    | '/admin/database-status'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes/$id/editar'
    | '/propostas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/propostas'
    | '/admin/database-status'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes/$id/editar'
    | '/propostas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PropostasRoute: typeof PropostasRouteWithChildren
  AdminDatabaseStatusRoute: typeof AdminDatabaseStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/nova': {
      id: '/propostas/nova'
      path: '/nova'
      fullPath: '/propostas/nova'
      preLoaderRoute: typeof PropostasNovaRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/admin/database-status': {
      id: '/admin/database-status'
      path: '/admin/database-status'
      fullPath: '/admin/database-status'
      preLoaderRoute: typeof AdminDatabaseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id/editar': {
      id: '/propostas/$id/editar'
      path: '/editar'
      fullPath: '/propostas/$id/editar'
      preLoaderRoute: typeof PropostasIdEditarRouteImport
      parentRoute: typeof PropostasIdRoute
    }
    '/clientes/$id/editar': {
      id: '/clientes/$id/editar'
      path: '/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof ClientesIdEditarRouteImport
      parentRoute: typeof ClientesIdRoute
    }
  }
}

interface ClientesIdRouteChildren {
  ClientesIdEditarRoute: typeof ClientesIdEditarRoute
}

const ClientesIdRouteChildren: ClientesIdRouteChildren = {
  ClientesIdEditarRoute: ClientesIdEditarRoute,
}

const ClientesIdRouteWithChildren = ClientesIdRoute._addFileChildren(
  ClientesIdRouteChildren,
)

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRouteWithChildren
  ClientesNovoRoute: typeof ClientesNovoRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRouteWithChildren,
  ClientesNovoRoute: ClientesNovoRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface PropostasIdRouteChildren {
  PropostasIdEditarRoute: typeof PropostasIdEditarRoute
}

const PropostasIdRouteChildren: PropostasIdRouteChildren = {
  PropostasIdEditarRoute: PropostasIdEditarRoute,
}

const PropostasIdRouteWithChildren = PropostasIdRoute._addFileChildren(
  PropostasIdRouteChildren,
)

interface PropostasRouteChildren {
  PropostasIdRoute: typeof PropostasIdRouteWithChildren
  PropostasNovaRoute: typeof PropostasNovaRoute
}

const PropostasRouteChildren: PropostasRouteChildren = {
  PropostasIdRoute: PropostasIdRouteWithChildren,
  PropostasNovaRoute: PropostasNovaRoute,
}

const PropostasRouteWithChildren = PropostasRoute._addFileChildren(
  PropostasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PropostasRoute: PropostasRouteWithChildren,
  AdminDatabaseStatusRoute: AdminDatabaseStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
